### ISSUE TITLE
"Anteil in %" kommt ohne Dezimalstelle

### ISSUE THREAD

**Issue by Luescher** [sogis/pdf4oereb#27]
Im XML PartInPercent auf 1 Stelle nach dem Komma. Das soll so im PDF übernommen werden.

Beispiel zum testen...
[https://geo-t.so.ch/api/oereb/v1/extract/reduced/xml/geometry/CH380932068175](https://geo-t.so.ch/api/oereb/v1/extract/reduced/xml/geometry/CH380932068175)
[https://geo-t.so.ch/map?oereb_egrid=CH380932068175](https://geo-t.so.ch/map?oereb_egrid=CH380932068175)

**Comment by edigonzales** [comment]
fixed https://github.com/openoereb/pdf4oereb/commit/f3e47ab26cdecc0ad0388bb14c195bef72dccc80
