### ISSUE TITLE
Text zwischen zwei Linien nicht in der Mitte

### ISSUE THREAD

**Issue by Luescher** [sogis/pdf4oereb#28]
Ich habe das PDF ausgedruckt und mit den Kantonen Uri und BL verglichen. 
Mein Fazit... Uri und BL haben Fehler...

Aber was ich gesehen habe, dass der Text z.B. auf Seite 1 zwischen den Linien irgendwie nicht in der Mitte ist (oben ca 1.5 mm / unten 2.2 mm). In der Weisung sieht es so aus als sei der Text in der Mitte.
[CH868832067772_Kontrolle.pdf](https://github.com/openoereb/pdf4oereb/files/3944073/CH868832067772_Kontrolle.pdf)

**Comment by edigonzales** [comment]
Ich bin eben nicht sicher, ob das wirklich 100%ig sauber gemittet werden kann. Bei Kleinbuchstaben ist die Mittag anders als bei Grossbuchstaben und Grossbuchstaben haben auch nicht zwingend die gleich Höhe. Ich erinnere mich daran, hier rumgebastelt zu haben. Ich schaue es nochmals an, ob ich dann bei den hinteren Seiten nicht schlauer geworden bin.

btw: Hintergrundkarte bei den ÖREB-Seiten ist immer noch grau (transparent) statt schwarz.

**Comment by Luescher** [comment]
Konntest du das ansehen?

**Comment by edigonzales** [comment]
Ja. Jedenfalls wurde ich bei den hinteren Seiten nicht schlauer. Ich mache einen "enhancement" draus. Dann kann man nochmals drüber wenn wir an die neue Weisung anpassen.

**Comment by edigonzales** [comment]
fixed
