### ISSUE TITLE
Seite 1 soll "Grundbuch" stehen und nicht "Grundbuchkreis"

### ISSUE THREAD

**Issue by Luescher** [sogis/pdf4oereb#30]
M-07 (Abnahmeprotokoll). 
Gibt im Kanton eben nicht eine ganz klare Bezeichnung. Für den Benutzer ist «Grundbuch» sicher verständlicher.

- Intercapi steht "Gemeinde"
- in unserem Objektblatt steht "Grundbuch"

**Comment by edigonzales** [comment]
fixed: https://github.com/openoereb/pdf4oereb/commit/1f5e91a3792f28842061b6630d56953350560f35

https://geo-t.so.ch/api/oereb/extract/reduced/pdf/CH956732730671

[CH956732730671.pdf](https://github.com/openoereb/pdf4oereb/files/4448617/CH956732730671.pdf)
